#服务器端口号
server:
  port: 8080

#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_project_database?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
mybatis:
  mapper-locations: classpath:/mapper/*.xml # mapper映射文件路径
  type-aliases-package: com.recommend.entity # 该package下的类将具有默认别名